jobs:
  build_and_deploy:
    name: Build package and deploy to myWindowsHosting.com
    runs-on: windows-latest
    steps:
      - name: build file
        uses: actions/checkout@v4

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: win8189.site4now.net
          username: websiteuae-001
          password: PPpp77ViWN
